export const SUPPORTED_LOCALES = ['en', 'pt-BR'] as const;

export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

type TranslationMap = Record<string, string>;

const messages: Record<SupportedLocale, TranslationMap> = {
  en: {
    'common.back': 'Back',
    'common.next': 'Next',
    'common.learnMore': 'Learn more',
    'common.loading': 'Loading...',
    'starter.connectDataSourceTitle': 'Connect a data source',
    'starter.voteDataSourcePrefix': 'Vote for your favorite data sources on',
    'starter.playSampleDataTitle': 'Play around with sample data',
    'connectDataSource.title': 'Connect the data source',
    'connectDataSource.setupGuideText': 'Learn more information in the {{label}} setup guide.',
    'selectModels.title': 'Select tables to create data models',
    'selectModels.description':
      'We will create data models based on selected tables to help AI better understand your data.',
    'selectModels.aboutDataModels': 'about data models.',
    'selectModels.tableName': 'Table name',
    'defineRelations.title': 'Define relationships',
    'defineRelations.description':
      'You can create relationships between selected tables. We provide suggested relationships based on primary and foreign keys defined in your data source. The relationships are then added to data models.',
    'defineRelations.noRecommendedTitle': 'No recommended relationships',
    'defineRelations.noRecommendedDescription':
      'No relationships are recommended because no primary or foreign keys were detected.',
    'defineRelations.from': 'From',
    'defineRelations.to': 'To',
    'defineRelations.type': 'Type',
    'defineRelations.autoGenerated': '(auto-generated)',
    'defineRelations.confirmDelete': 'Confirm to delete?',
    'defineRelations.delete': 'Delete',
    'defineRelations.addRelationship': 'Add relationship',
    'defineRelations.add': 'Add',
    'defineRelations.skipStep': 'Skip this step',
    'defineRelations.finish': 'Finish',
    'emptyDashboard.noCharts': 'No charts have been added yet',
    'emptyDashboard.stepsDescription': 'Follow these steps to pin charts to your dashboard.',
    'emptyDashboard.step1': '1. Create a thread',
    'emptyDashboard.step2': '2. Generate a chart',
    'emptyDashboard.step3': '3. Pin to dashboard',
    'recommendedQuestions.title': 'Know more about your data.',
    'recommendedQuestions.subtitle': 'Try asking some of the following questions',
    'recommendedQuestions.collapse': 'Collapse',
    'recommendedQuestions.expandAll': 'Expand all',
    'demoPrompt.tryAsking': 'Try asking...',
    'stories.next': 'Next',
    'stories.previous': 'Previous',
    'stories.dataModelingGuide.title': 'Data modeling guide',
    'stories.dataModelingGuide.description':
      'Data modeling adds a logical layer over your original data schema, organizing relationships, semantics, and calculations. This helps AI align with business logic, retrieve precise data, and generate meaningful insights.',
    'stories.dataModelingGuide.moreDetails': 'More details',
    'stories.dataModelingGuide.sampleIntro': 'We use {{label}} Dataset to present the guide.',
    'stories.dataModelingGuide.sampleLink': 'about the {{label}} Dataset.',
    'stories.dataModelingGuide.createModel': 'Create a model',
    'stories.dataModelingGuide.createModelDescription': 'Click the add icon to start create your first model.',
    'stories.dataModelingGuide.editModel': 'Edit a model',
    'stories.dataModelingGuide.editModelDescription': 'Click the more icon to update the columns of model or delete it.',
    'stories.dataModelingGuide.editMetadata': 'Edit metadata',
    'stories.dataModelingGuide.editMetadataDescription':
      'You could edit alias (alternative name) and descriptions of models and columns.',
    'stories.dataModelingGuide.deployModeling': 'Deploy modeling',
    'stories.dataModelingGuide.deployModelingDescription':
      'After editing the models, remember to deploy the changes.',
    'stories.dataModelingGuide.askQuestions': 'Ask questions',
    'stories.dataModelingGuide.askQuestionsDescription':
      'When you finish editing your models, you can visit "Home" and start asking questions.',
    'stories.dataModelingGuide.goToHome': 'Go to Home',
    'stories.languageSwitcher.label': 'Project language',
    'stories.switchLanguage.title': 'Switch the language',
    'stories.switchLanguage.descriptionStart':
      'Choose your preferred language. Once set up, AI will respond in your chosen language.',
    'stories.switchLanguage.descriptionEnd':
      'You can go to project settings to change it if you change your mind.',
    'stories.switchLanguage.submit': 'Submit',
    'stories.knowledgeGuide.questionSqlTitle': 'Build knowledge base: Question-SQL pairs',
    'stories.knowledgeGuide.questionSqlDescription':
      'Create and manage Question-SQL pairs to refine Wren AI\'s SQL generation. You can manually add pairs here or go to Home, ask a question, and save the correct answer to Knowledge. The more you save, the smarter Wren AI becomes!',
    'stories.knowledgeGuide.instructionsTitle': 'Build knowledge base: Instructions',
    'stories.knowledgeGuide.instructionsDescription':
      'In addition to Question-SQL pairs, you can create instructions to define business rules and query logic. These rules guide Wren AI in applying consistent filters, constraints, and best practices to SQL queries.',
    'stories.gotIt': 'Got it',
    'stories.saveToKnowledge.title': 'Save to knowledge',
    'stories.saveToKnowledge.description':
      'If the AI-generated answer is correct, save it as a Question-SQL pair to improve AI learning. If it\'s incorrect, refine it with follow-ups before saving to ensure accuracy.',
  },
  'pt-BR': {
    'common.back': 'Voltar',
    'common.next': 'Avançar',
    'common.learnMore': 'Saiba mais',
    'common.loading': 'Carregando...',
    'starter.connectDataSourceTitle': 'Conecte uma fonte de dados',
    'starter.voteDataSourcePrefix': 'Vote nas suas fontes de dados favoritas no',
    'starter.playSampleDataTitle': 'Explore os dados de exemplo',
    'connectDataSource.title': 'Conecte a fonte de dados',
    'connectDataSource.setupGuideText': 'Veja mais informações no guia de configuração de {{label}}.',
    'selectModels.title': 'Selecione tabelas para criar modelos de dados',
    'selectModels.description':
      'Vamos criar modelos de dados com base nas tabelas selecionadas para ajudar a IA a entender melhor seus dados.',
    'selectModels.aboutDataModels': 'sobre modelos de dados.',
    'selectModels.tableName': 'Nome da tabela',
    'defineRelations.title': 'Defina relacionamentos',
    'defineRelations.description':
      'Você pode criar relacionamentos entre as tabelas selecionadas. Fornecemos sugestões de relacionamentos com base em chaves primárias e estrangeiras definidas na sua fonte de dados. Em seguida, os relacionamentos são adicionados aos modelos de dados.',
    'defineRelations.noRecommendedTitle': 'Sem relacionamentos recomendados',
    'defineRelations.noRecommendedDescription':
      'Nenhum relacionamento foi recomendado porque nenhuma chave primária ou estrangeira foi detectada.',
    'defineRelations.from': 'De',
    'defineRelations.to': 'Para',
    'defineRelations.type': 'Tipo',
    'defineRelations.autoGenerated': '(gerado automaticamente)',
    'defineRelations.confirmDelete': 'Confirmar exclusão?',
    'defineRelations.delete': 'Excluir',
    'defineRelations.addRelationship': 'Adicionar relacionamento',
    'defineRelations.add': 'Adicionar',
    'defineRelations.skipStep': 'Pular esta etapa',
    'defineRelations.finish': 'Concluir',
    'emptyDashboard.noCharts': 'Nenhum gráfico foi adicionado ainda',
    'emptyDashboard.stepsDescription': 'Siga estas etapas para fixar gráficos no seu dashboard.',
    'emptyDashboard.step1': '1. Criar uma thread',
    'emptyDashboard.step2': '2. Gerar um gráfico',
    'emptyDashboard.step3': '3. Fixar no dashboard',
    'recommendedQuestions.title': 'Saiba mais sobre seus dados.',
    'recommendedQuestions.subtitle': 'Tente fazer algumas das perguntas abaixo',
    'recommendedQuestions.collapse': 'Recolher',
    'recommendedQuestions.expandAll': 'Expandir tudo',
    'demoPrompt.tryAsking': 'Tente perguntar...',
    'stories.next': 'Próximo',
    'stories.previous': 'Anterior',
    'stories.dataModelingGuide.title': 'Guia de modelagem de dados',
    'stories.dataModelingGuide.description':
      'A modelagem de dados adiciona uma camada lógica sobre seu esquema original, organizando relacionamentos, semântica e cálculos. Isso ajuda a IA a se alinhar com a lógica de negócio, recuperar dados com precisão e gerar insights relevantes.',
    'stories.dataModelingGuide.moreDetails': 'Mais detalhes',
    'stories.dataModelingGuide.sampleIntro': 'Usamos o dataset {{label}} para apresentar o guia.',
    'stories.dataModelingGuide.sampleLink': 'sobre o dataset {{label}}.',
    'stories.dataModelingGuide.createModel': 'Criar um modelo',
    'stories.dataModelingGuide.createModelDescription': 'Clique no ícone de adicionar para criar seu primeiro modelo.',
    'stories.dataModelingGuide.editModel': 'Editar um modelo',
    'stories.dataModelingGuide.editModelDescription': 'Clique no ícone de mais para atualizar as colunas do modelo ou excluí-lo.',
    'stories.dataModelingGuide.editMetadata': 'Editar metadados',
    'stories.dataModelingGuide.editMetadataDescription':
      'Você pode editar alias (nome alternativo) e descrições de modelos e colunas.',
    'stories.dataModelingGuide.deployModeling': 'Publicar modelagem',
    'stories.dataModelingGuide.deployModelingDescription':
      'Depois de editar os modelos, lembre-se de publicar as alterações.',
    'stories.dataModelingGuide.askQuestions': 'Fazer perguntas',
    'stories.dataModelingGuide.askQuestionsDescription':
      'Quando terminar de editar seus modelos, você pode ir para "Home" e começar a fazer perguntas.',
    'stories.dataModelingGuide.goToHome': 'Ir para Home',
    'stories.languageSwitcher.label': 'Idioma do projeto',
    'stories.switchLanguage.title': 'Trocar idioma',
    'stories.switchLanguage.descriptionStart':
      'Escolha seu idioma preferido. Depois da configuração, a IA responderá no idioma escolhido.',
    'stories.switchLanguage.descriptionEnd':
      'Você pode ir para as configurações do projeto para mudar depois, se quiser.',
    'stories.switchLanguage.submit': 'Salvar',
    'stories.knowledgeGuide.questionSqlTitle': 'Base de conhecimento: pares Pergunta-SQL',
    'stories.knowledgeGuide.questionSqlDescription':
      'Crie e gerencie pares Pergunta-SQL para refinar a geração de SQL do Wren AI. Você pode adicionar pares manualmente aqui ou ir para Home, fazer uma pergunta e salvar a resposta correta em Knowledge. Quanto mais você salva, mais inteligente o Wren AI fica!',
    'stories.knowledgeGuide.instructionsTitle': 'Base de conhecimento: Instrucoes',
    'stories.knowledgeGuide.instructionsDescription':
      'Além dos pares Pergunta-SQL, você pode criar instruções para definir regras de negócio e lógica de consulta. Essas regras orientam o Wren AI a aplicar filtros, restrições e boas práticas de forma consistente nas consultas SQL.',
    'stories.gotIt': 'Entendi',
    'stories.saveToKnowledge.title': 'Salvar em knowledge',
    'stories.saveToKnowledge.description':
      'Se a resposta gerada pela IA estiver correta, salve como um par Pergunta-SQL para melhorar o aprendizado. Se estiver incorreta, refine com perguntas de follow-up antes de salvar para garantir precisão.',
  },
};

export const normalizeLocale = (locale?: string): SupportedLocale => {
  if (!locale) return 'en';
  if (locale.toLowerCase().startsWith('pt')) return 'pt-BR';
  return 'en';
};

const getValue = (locale: SupportedLocale, key: string): string | undefined => {
  return messages[locale][key];
};

export const t = (
  locale: string | undefined,
  key: string,
  variables?: Record<string, string | number>,
) => {
  const normalizedLocale = normalizeLocale(locale);
  const template = getValue(normalizedLocale, key) ?? getValue('en', key) ?? key;
  if (!variables) return template;

  return Object.entries(variables).reduce((acc, [varKey, value]) => {
    return acc.replace(new RegExp(`{{${varKey}}}`, 'g'), String(value));
  }, template);
};
